repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ['--disable=missing-module-docstring,logging-fstring-interpolation', '--max-line-length=120']
